---
title: "Análise de Regressão"
author:
  - name: Prof. Dr. Juliano Bortolini
    email: profjulianobortolini@gmail.com
    url: http://www.julianobortolini.com.br
    affiliations:
      - name: Universidade Federal de Mato Grosso
format:
  html:
    embed-resources: true
engine: knitr
---

*Bacharelado em Estatística - UFMT*

*Período letivo: 2025/1*

### Avisos:

-   Última atualização do site às **`r format(Sys.time(), "%H:%M", tz='America/Cuiaba')`** do dia **`r format(Sys.time(), "%d/%m/%Y")`**.
-   Monitor: Heliton (quarta-feira das 18 às 19h)
-   Avaliação 1: escrita. Data: **30/7/2025**. Conteúdo: correlação e regressão linear simples.
-   Relatório parcial: entrega do relatório parcial de análise de dados (etapa 1). Data: **4/8/2025**
-   Avaliação 2: escrita, computacional e oral. Data: **17/9/2025**. Conteúdo: toda a disciplina.


### Ementa:

Análise de correlação. Regressão linear simples e múltipla. Regressão com variáveis qualitativas. Técnicas de diagnóstico em regressão. Seleção de variáveis e construção de modelos. Validação de modelos. Transformação de variáveis.

### Notas de aula:

-   Aulas 1 e 2: Apresentação da disciplina com ementa e avaliações. Introdução ao estudo de regressão a partir do artigo seminal de Francis Galton (1886): [Regression towards mediocrity in hereditary stature](https://zenodo.org/records/1449548), no qual se analisa a relação entre as estaturas de filhos e filhas em função das estaturas de pais e mães, destacando-se a tendência de regressão à média (aproximadamente 2/3). Exploração da obtenção de modelos por meio de equações diferenciais. Estudo do modelo de crescimento e decaimento exponencial. Introdução ao modelo de regressão linear simples, exemplificado pela relação entre tempo e distância de deslocamento. Ampliação para o modelo de regressão linear múltipla, incluindo variáveis indicadoras e efeitos de interação (por exemplo, a interação entre distância de deslocamento e o horário em que ocorre). Aplicações adicionais incluem a modelagem de relações entre variáveis em instrumentos psicométricos (escores) e a utilização de modelos de dose-resposta, com destaque para o modelo logístico.


-   Aula 3: definição de covariância, ilustração do porquê dos valores positivos ou negativos da covariância, proposições/propriedades de covariância, definição de correlação, proposições/propriedades, estimador para a covariância e correlação, exemplo de cálculo de covariância e correlação com dados reais (consumo de açúcar e taxa de depressão), teste de hipóteses para correlação (teste 1: $H_0: \rho = 0$ versus $H_1: \rho \neq 0$ e teste 2: $H_0: \rho = \rho_0$ versus $H_1: \rho \neq \rho_0$) e exercício de teste de hipóteses para correlação. **Tarefa para casa:** correlação como medida de proporção entre duas variáveis (padronizadas) $Z_1 = k Z_2$.


-   [Lista 1](lista1_2025-1.html): covariância e correlação.

-   Aula 4: apresentação da definição formal do modelo de regressão, com exemplo motivacional. Construção e interpretação do gráfico de dispersão para visualização da relação entre duas variáveis. Modelo de regressão linear simples, com detalhamento de suas componentes e respectivas interpretações. Cálculo da média e da variância condicional de $Y$ dado $x$, $E(Y|x)$ e $\text{Var}(Y|x)$, com representação gráfica da reta de regressão e das curvas de densidade associadas. Discussão sobre o conceito de variância constante (homocedasticidade) e suas implicações para o ajuste do modelo. Definição do modelo de regressão linear múltipla, com apresentação de casos particulares, como o modelo de regressão polinomial. Distinção entre relação linear (ou não linear) entre variáveis e relação linear (ou não linear) entre os parâmetros do modelo. Estudo da estimação dos parâmetros do modelo de regressão linear simples por meio do método dos mínimos quadrados, acompanhado de um exemplo ilustrativo. **Tarefa:** estudar o método de estimação de máxima verossimilhanca, testes de hipóteses e intervalos de confiança para parâmetros.


-   [Lista 2](lista2_2025-1.html): um pouco mais sobre covariância e correlação.


-   [Lista 3](lista3_2025-1.html): ajuste de modelos de regressão linear simples.


-   Aula 5: estimação de $\sigma^2$ ($\hat{\sigma}^2 = QMErro$, quadrado médio do erro), propriedades dos estimadores de mínimos quadrados para os parâmetros $\beta_0$ e $\beta_1$, esperança e variância, distribuição de probabilidade dos estimadores (beta0 e beta1), intervalos de confiança e testes de hipóteses (Wald), exemplo de IC e TH para os parâmetros.

-   Aula 6: desenvolvimento da expressão $SQErro = SQTotal - SQReg = S_{yy} - \hat{\beta}_1Sxy$, intervalo de confiança para o valor estimado (média), intervalo de predição (novas observações ou observações futuras) e exemplo. Lembrete: próxima aula será a avaliação teórica. É permitida a consulta a qualquer material, exceto celular e computador.

-   [Lista 4](lista4_2025-1.html): ajuste de modelos de regressão linear simples e inferência estatística (intervalos de confiança e testes de hipóteses).

-   [Relatório](trabalho_2025-1.html): orientações para a entrega do relatório parcial de análise de dados (etapa 1). Data da entrega: 4/8/2025.


-   Aula 7: avaliação 1 (escrita).

-  Aula 8: definição de modelo de regressão linear múltipla, efeitos simples e de interação, modelo na forma matricial, estimação de parâmetros pelo método de mínimos quadrados pelo método escalar e matricial, exemplo de estimação, propriedades dos estimadores de mínimos quadrados, esperança e variância dos estimadores (erro padrão), estimação de sigma2, método de estimação da máxima verossimilhança, teste de hipóteses para regressão e coeficientes, exemplos de teste de hipóteses, intervalos de confiança para parâmetros, valor médio e novas observações e exemplos de intervalos de confiança.

-   Aula 9: revisão da aula anterior, intervalos de confiança para parâmetros, valor médio e novas observações, exemplos de intervalos de confiança.

-   [Lista 5](lista5_2025-1.html): ajuste de modelos de regressão linear múltipla e inferência estatística (intervalos de confiança e testes de hipóteses).

-   Aula 10: Análise de pressupostos, pontos influentes e discrepantes, regressão polinomial e variáveis indicadoras.


-   Aula 11: regressão com suporte computacional. [Rotina computacional](reg_comp.html).




- [Lista 6](lista6.html): ajuste de modelos de regressão linear múltipla, inferência estatística, análise de pressupostos, pontos influentes e discrepantes, regressão polinomial e variáveis indicadoras.


- Aula 12: aula prática. Experimento de helicóptero de papel.


- Aula 13: [avaliação 2](prova2_2025-1.html). Atenção: entregar até às 23:59 do dia 18/9/2025, no AVA.


- Aula 14: entrega do trabalho final (relatório de análise de dados). Data: 22/9/2025.

<!-- -   Aula 1: apresentação do plano de ensino e introdução à regressão baseado no artigo de [Galton](https://zenodo.org/records/1449548) (1886). -->

<!--     *Referência:* Galton, F. (1886). "Regression towards mediocrity in hereditary stature". *The Journal of the Anthropological Institute of Great Britain and Ireland*. **15**: 246-263. -->

<!-- -   Aula 2: definição de covariância, ilustração do porquê dos valores positivos ou negativos da covariância, proposições/propriedades de covariância, definição de correlação, proposições/propriedades, função de distribuição acumulada empírica, teorema de Glivenko-Cantelli, teorema (estimador para a transformação $T(F) = \int f(x) dF$), estimador para a covariância e correlação, propriedades dos estimadores da covariância e correlação e exemplo com dados reais. -->

<!-- -   [Lista 1](lista1.html): covariância e correlação. -->

<!-- -   Aula 3: revisão da aula 2, correlação como medida de proporção entre duas variáveis (padronizadas), estimação da relação funcional (modelo) entre duas variáveis, estimação de beta_0 e beta_1, exemplo com os dados de consumo de açúcar e taxa de depressão, correlação entre duas variáveis normais, estimação do modelo linear (reta) entre duas variáveis normais, comentários sobre correlação de Pearson (dados normais) e Spearman (postos dos dados), teste de hipóteses para correlação: 1) H_0: rho = 0 e 2) H_0: rho = rho_0 e exercício de teste de hipóteses para correlação. -->

<!-- -   [Lista 2](lista2.html): fórmula da correlação amostral e de Spearman. -->

<!-- -   Aula 4: definição de modelo de regressão linear simples, diferentes métodos de calcular distâncias entre pontos (sugestão: leitura do livro do Rao (2008)), estimação de parâmetros beta_0 e beta_1 pelo método de mínimos quadrados, exemplo de estimação (exemplo foguete), propriedades dos estimadores de mínimos quadrados, esperança e variância dos estimadores (erro padrão), teorema de Gauss-Markov (estimadores não viciados e de variância mínima, BLUE). -->

<!-- -   Aula 5: revisão da aula 4, modelo de regressão linear simples com variância constante e variância dependente de covariáveis, estimação de sigma (quadrado médio do erro), teste de hipóteses para regressão (análise de variância), desenvolvimento da análise de variância (Fisher), teste de hipóteses Wald (teste t) para beta_1 e beta_0, relação entre os testes t e F (t\^2 = F), intervalos de confiança para beta_0 e beta_1 (fazer exercício), ic para sigma\^2, sigma e cv (exercício). -->

<!-- -   [Lista 3](lista3.html): regressão linear simples. -->

<!-- -   Aula 6: intervalo de confiança para valor estimado, intervalo de predição, coeficiente de determinação, regressão pela origem e estimação por máxima verossimilhança. -->

<!-- -   [lista 4](lista4.html): regressão linear simples. -->

<!-- -   Aula 7: aula prática de resolução da [lista 4](lista4.html). -->

<!-- -   Aula 8: definição de modelo de regressão linear múltipla, efeitos simples e de interação, modelo na forma matricial, estimação de parâmetros pelo método de mínimos quadrados pelo método escalar e matricial, exemplo de estimação, propriedades dos estimadores de mínimos quadrados, esperança e variância dos estimadores (erro padrão), estimação de sigma2, método de estimação da máxima verossimilhança, teste de hipóteses para regressão e coeficientes, exemplos de teste de hipóteses, intervalos de confiança para parâmetros, valor médio e novas observações e exemplos de intervalos de confiança. *Tarefa para casa: estudar sobre R2 ajustado, comparação entre modelo completo e reduzido, intervalos de confiança simultâneos (região de confiança) para os parâmetros, coeficientes padronizados (coeficientes beta) e multicolinearidade (sugestão: livro do Montgomery).* -->

<!-- -   [Lista 5](lista5.html): regressão linear múltipla. -->

<!-- -   Aula 9: **aviso que na próxima aula será a avaliação 1**. Revisão da aula anterior, intervalos de confiança para parâmetros, valor médio e novas observações, exemplos de intervalos de confiança. Cálculos usando o software R: [exemplo_rlm.R](exemplo_rlm.R). *Tarefa para casa: estudar sobre R2 ajustado, comparação entre modelo completo e reduzido, intervalos de confiança simultâneos (região de confiança) para os parâmetros, coeficientes padronizados (coeficientes beta) e multicolinearidade (sugestão: livro do Montgomery).* -->

<!-- -   Aula 10: avaliação 1 (escrita e computacional). A arguição oral será na próxima aula (Aula 11). -->

<!-- -   Aula 11: avaliação 1 (arguição oral). -->


<!-- -   Aula 12: regressão com suporte computacional. [Rotina computacional](reg_comp.html). *Tarefa (1 ponto extra na avaliação 1): refazer a avaliação 1 ([escrita](prova1.pdf) e [computacional](prova1comp.pdf)) usando a rotina da aula.*  -->


<!-- -   Aula 13: Análise de pressupostos, pontos influentes e discrepantes, regressão polinomial e variáveis indicadoras. [Rotina computacional](reg_comp.html). -->


<!-- -   Aula 14: Resolver a [lista 6](lista6.html) ([gabarito](lista6_gab.html), sem os comentários e justificativas nas resoluções). Conteúdos adicionais: teste F parcial para modelos de efeitos aleatórios (comparação de modelos de efeito fixo e efeito misto), multicolinearidade, métodos *forward*, *backward* e *stepwise* para seleção de variáveis e métodos *leave-one-out*, *leave-p-out* e *k-fold* para validação de modelos (validação cruzada). -->


<!-- -   Aula 15 (30/4/2025): avaliação 2 (escrita, computacional e arquição oral) com todo o conteúdo da disciplina. -->

<!-- -   [Avaliação 2](prova2.html) -->

<!-- -   Aula 16 (9/5/2025): entrega da avaliação 3 (relatório de análise de dados). -->


### Avaliações:

-   $A_1$: escrita, computacional e arguição oral. Nota: 0 a 10.

*Conteúdo:* análise de correlação, regressão linear simples e múltipla.

-   $A_2$: escrita, computacional e arguição oral. Nota: 0 a 10.

*Conteúdo:* todo o conteúdo da disciplina.

-   $A_{31}$: relatório parcial de análise de dados. Nota: 0 a 5.

-   $A_{32}$: relatório final de análise de dados. Nota: 0 a 5.



A média final ($MF$) será calculada por:

$$MP = 0,4 A_1 + 0,4 A_2 + 0,2(A_{31} + A_{32}).$$

Se $MF \geq 5$, o aluno será aprovado. Não haverá prova final.


### Livro texto:

Montgomery, D. C., Peck, E. A., & Vining, G. G. (2021). *Introduction to linear regression analysis* (6th ed.). Wiley.

### Referências:

Devore, J. L., Berk, K. N., & Carlton, M. A. (2021). *Modern mathematical statistics with applications* (3rd ed.). Springer.

Seber, G. A. F., & Lee, A. J. (2012). *Linear Regression Analysis* (2nd ed.). Wiley.

Draper, N. R., & Smith, H. (1998). *Applied regression analysis* (3rd ed.). Wiley.

Rao, C. R., Toutenburg, H., Shalabh, & Heumann, C. (2008). *Linear Models and Generalizations: Least Squares and Alternatives* (3rd ed.). Springer.

Allen, M. P. (1997). *Understanding Regression Analysis*. Sage Publications.

Kutner, M. H., Nachtsheim, C. J., Neter, J., & Li, W. (2005). *Applied linear statistical models* (5th ed.). McGraw-Hill.

Rencher, A. C., & Schaalje, G. B. (2008). *Linear models in statistics* (2nd ed.). Wiley.

Faraway, J. J. (2015). *Linear Models with R*. CRC Press.

------------------------------------------------------------------------

::: {style="text-align: center;"}
[\@profjulianobortolini](https://instagram.com/profjulianobortolini)      [www.julianobortolini.com.br](http://www.julianobortolini.com.br)      [linkedin](https://linkedin.com/in/julianobortolini)      [github](https://github.com/julianobortolini)       [lattes](http://lattes.cnpq.br/6210909768845403)
:::
