---
title: "Análise de Regressão"
author:
  - name: Prof. Dr. Juliano Bortolini
    email: profjulianobortolini@gmail.com
    url: http://www.julianobortolini.com.br
    affiliations:
      - name: Universidade Federal de Mato Grosso
format:
  html:
    embed-resources: true
engine: knitr
---

*Bacharelado em Estatística - UFMT*

*Período letivo: 2024/2*

### Lista de exercícios 4


1. 'O artigo *“A Cross-National Relationship Between Sugar Consumption and Major Depression?”* (*Depression and Anxiety* 2002: 118–120) relatou os seguintes dados sobre $x =$ consumo diário de açúcar (calorias per capita) e $y =$ taxa anual de depressão majoritária (casos por 100 pessoas) para uma amostra de seis países.

```{r, echo=FALSE}
library(knitr)

dados <- data.frame(
  Country = c("USA", "Canada", "France", "Germany", "New Zealand", "South Korea"),
  `Sugar consumption` = c(300, 390, 350, 375, 480, 150),
  `Depression rate` = c(3.0, 5.2, 4.4, 5.0, 5.7, 2.3)
)

kable(dados, caption = "Consumo diário de açúcar e taxa anual de depressão por país")
```

a. Construa o gráfico de dispersão dos dados. Há evidência visual de relação linear entre as variáveis?

b. Calcule as quantidades: $\sum x_i$, $\sum y_i$, $\sum x_i^2$, $\sum y_i^2$, $\sum x_i y_i$, $\bar{x}$, $\bar{y}$, $S_{xx}$, $S_{yy}$ e $S_{xy}$.

c. Calcule o coeficiente de correlação entre as duas variáveis. Há evidência de correlação linear entre as variáveis?

d. Verifique se a correlação é significativa a um nível de significância de $5\%$. Construa o intervalo de confiança de $95\%$ para o coeficiente de correlação.

e. Ajuste um modelo de regressão linear simples relacionando a taxa de depressão ao consumo diário de açúcar.

f. Construa a tabela de análise de variância e teste a significância da regressão.

g. Qual porcentagem da variabilidade total em $y$ é explicada por este modelo?

h. Calcule os erros-padrões do coeficiente angular e do coeficiente linear.

i. Calcule o intervalo de confiança de $95\%$ para o coeficiente angular e interprete-o.

j. Realize o teste t para o coeficiente angular. Há evidência de que o consumo diário de açúcar afeta a taxa de depressão? Essa conclusão já foi obtida anteriormente?

k. Encontre um intervalo de confiança de $95\%$ para a taxa média de depressão se o consumo diário de açúcar for limitado a 350 calorias.

l. Encontre um intervalo de confiança de $90\%$ para a taxa média de depressão se o consumo diário de açúcar for limitado a 350 calorias.

m. Encontre um intervalo de predição de $95\%$ para a taxa média de depressão se o consumo diário de açúcar for limitado a 400 calorias.

n. Encontre um intervalo de predição de $90\%$ para a taxa média de depressão se o consumo diário de açúcar for limitado a 400 calorias.

o. Apresente uma expressão para o intervalo de confiança de $95\%$ para a taxa média de depressão se o consumo diário de açúcar for $x$.

p. Apresente uma expressão para o intervalo de predição de $95\%$ para a taxa média de depressão se o consumo diário de açúcar for $x$.





------------------------------------------------------------------------

::: {style="text-align: center;"}
[\@profjulianobortolini](https://instagram.com/profjulianobortolini)      [www.julianobortolini.com.br](http://www.julianobortolini.com.br)      [linkedin](https://linkedin.com/in/julianobortolini)      [github](https://github.com/julianobortolini)       [lattes](http://lattes.cnpq.br/6210909768845403)
:::
