---
title: "Análise de Regressão"
author:
  - name: Prof. Dr. Juliano Bortolini
    email: profjulianobortolini@gmail.com
    url: http://www.julianobortolini.com.br
    affiliations:
      - name: Universidade Federal de Mato Grosso
format:
  pdf:
    embed-resources: true
engine: knitr
---

*Bacharelado em Estatística - UFMT*

*Período letivo: 2024/2*

### Avaliação 1 (computacional)



1. O artigo **“Ecofriendly Dyeing of Silk with Extract of Yerba Mate”** (Textile Res. J. 2017: 829–837) descreve um experimento para estudar os efeitos da concentração de corante (mg/L), da temperatura (°C) e do pH na adsorção de corante (mg de corante por grama de tecido). Adsorção de corante é um indicador de cor.

| Conc. | Temp. | pH  | Adsorção |
|------:|------:|----:|-----------:|
|   10  |   70  | 3,0 |        250 |
|   20  |   70  | 3,0 |        520 |
|   20  |   80  | 3,0 |        387 |
|   20  |   90  | 3,0 |        593 |
|   10  |   70  | 4,0 |        157 |
|   20  |   70  | 4,0 |        377 |
|   10  |   90  | 4,0 |        225 |
|   20  |   90  | 4,0 |        451 |
|   15  |   80  | 3,5 |        382 |
|   15  |   80  | 3,5 |        373 |


a. (1,00) Ajuste um modelo de regressão linear múltipla relacionando a adsorção com a concentração ($x_1$), temperatura ($x_2$) e pH ($x_3$), e interprete os coeficientes estimados.

b. (0,50) Construa a tabela de análise de variância (ANOVA) e teste a significância da regressão.

c. (0,50) Calcule as estatísticas $t$ para testar as hipóteses:

$H_0: \beta_1 = 0$,

$H_0: \beta_2 = 0$,

$H_0: \beta_3 = 0$.

Que conclusões você pode tirar sobre os papéis das variáveis $x_1$ (concentração), $x_2$ (temperatura) e $x_3$ (pH) no modelo?


d. (0,50) Encontre um intervalo de confiança (IC) de 95% para $\beta_1$ e interprete o resultado.

e. (0,50) Encontre um intervalo de confiança de 95% para a adsorção média quando $x_1 = 15$, $x_2 = 80$ e $x_3 = 3,5$.



<!-- ------------------------------------------------------------------------ -->

<!-- ::: {style="text-align: center;"} -->
<!-- [\@profjulianobortolini](https://instagram.com/profjulianobortolini)      [www.julianobortolini.com.br](http://www.julianobortolini.com.br)      [linkedin](https://linkedin.com/in/julianobortolini)      [github](https://github.com/julianobortolini)       [lattes](http://lattes.cnpq.br/6210909768845403) -->
<!-- ::: -->
